# Render Blueprint para Conselhos Esotéricos
# https://render.com/docs/blueprint-spec

services:
  # Web Service Principal
  - type: web
    name: conselhos-esotericos
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm ci && npm run build
    startCommand: node server/index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: NEON_DATABASE_URL
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: PORT
        value: 10000
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
    autoDeploy: true

# Nota: Banco de dados Neon já está configurado externamente
# ID do Projeto: royal-paper-66041902
# Configure DATABASE_URL nas variáveis de ambiente do Render
